name: Biweekly Report

on:
  schedule:
    - cron: '0 0 15 * *'
  workflow_dispatch:

jobs:
  create-report:
    runs-on: ubuntu-latest

    steps:
      - name: Send request to create biweekly report
        env:
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
        run: |
          curl -X POST https://finance-tracker-plum-six.vercel.app/api/cronjob/biweek-report \
          -H "Authorization: Bearer $CRON_SECRET"