name: Keep DB Alive

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  ping-db:
    runs-on: ubuntu-latest

    steps:
      - name: Send request to keep DB alive
        env:
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
        run: |
          curl -X POST https://www.moneyeye.dev/api/cronjob/keep-db-alive \
          -H "Authorization: Bearer $CRON_SECRET"